# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'TableViewDemo' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TableViewDemo
  pod 'FoldingCell'  
  target 'TableViewDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'TableViewDemoUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
